### ISSUE TITLE
Correspondance des dates incorrecte

### ISSUE THREAD

**Issue by NicooooGit** [delphiki/hass-pronote#11]
Hello,

J'ai un petit soucis dans les données récupérées. J'ai vu une personne avoir le même problème dans le git des card pour lovelace.

Les données de today sont celles d'hier, et celles de tomorrow/next day sont celles d'aujourd'hui.

Quelqu'un a le même souci ?

Merci d'avance
Nicolas

**Comment by NicooooGit** [comment]
https://github.com/delphiki/hass-pronote/pull/2#issuecomment-1624019312

**Comment by NicooooGit** [comment]
J'ai l'impression que je peux tricher en modifiant sensor.py:

lessons_today = await hass.async_add_executor_job(client.lessons, date.today())
    lessons_today = sorted(lessons_today, key=lambda lesson: lesson.start)

    lessons_tomorrow = await hass.async_add_executor_job(client.lessons, date.today() + timedelta(days=1))
    lessons_tomorrow = sorted(lessons_tomorrow, key=lambda lesson: lesson.start)

Si j'ajoute un jour de plus sur chaque sensor, je devrais tomber sur les bons jours, mais ça ne sera que temporaire et écrasé à la prochaine mise à jour... 

Si quelqu'un a une idée ? Même si j'ai un peu peur que ce soit dépendant de pronotepy...

**Comment by delphiki** [comment]
Hello @NicooooGit,

Quelle version de l'intégration est-ce que tu as ?
Hier soir j'ai publié une nouvelle version qui corrige les soucis de mises à jour des données qui ne se font pas correctement.

**Comment by NicooooGit** [comment]
J'ai mis à jour, rechargé mon intégration et reboot mon HA et c'est beaucoup mieux !

Merci pour le petit update :)
