### ISSUE TITLE
Ajout automatique de "?login=true"

### ISSUE THREAD

**Issue by GaPhi** [delphiki/hass-pronote#13]
En versions 0.6.0 et antérieures, il est impossible de se connecter avec l'URL : https://0951710t.index-education.net/pronote/parent.html

Il faut saisir, manuellement l'URL : https://0951710t.index-education.net/pronote/parent.html?login=true

L'ajout des paramètres de query 'login=true' devrait être automatique.

**Comment by delphiki** [comment]
Tu n'as pas besoin de mettre toute l'url, il suffit de mettre dans ton cas juste `https://0951710t.index-education.net/pronote/`

**Comment by GaPhi** [comment]
Comme il y a pas mal d'erreurs des utilisateurs sur cet URL, ne pourrait-on pas faire une regex pour extraire la partie utile quelque soit ce qui est saisi par l'utilisateur ?

Il y a aussi des erreurs sur l'ENT : le choix "laisser vide" devrait être le choix par défaut et mis en avant dans le libellé pour que l'utilisateur ne s'en préoccupe pas a priori, non ?

**Comment by GaPhi** [comment]
Le souci semble corrigé grâce aux QRcode
