### ISSUE TITLE
Remove false ERROR in logs

### ISSUE THREAD

**Issue by GaPhi** [delphiki/hass-pronote#17]
2023-09-15 16:12:57.734 ERROR (MainThread) [custom_components.pronote.coordinator] Error getting ical_url from pronote: Pronote did not return ICal token

Il ne s'agit pas d'une erreur mais d'une information lorsque les ical ne sont pas proposées par pronote, même s'il s'agit d'une exception au sens de l'informatique.

Peut-on déclasser ce log (et les similaires) pour alléger les fichiers système ?
Merci !

**Comment by vingerha** [comment]
L'erreur peut être correcte pour d'autre utilisateurs
Une solution devra avaoir l' 'option' pour recuperer calendrier (et menus...qui donne des fauses erreurs chez moi aussi)

**Comment by delphiki** [comment]
Corrigé, c'est désormais uniquement en info
