### ISSUE TITLE
Login with qrcode

### ISSUE THREAD

**Issue by Nemesis24** [delphiki/hass-pronote#31]
Bonjour, 
félicitations pour le travail accompli, malheureusement pour moi il m'est toujours impossible de me connecter, peut être que la connexion via qrcode pourrait solutionner mon problème.

[(https://pronotepy.readthedocs.io/en/stable/quickstart.html#logging-in-with-qr-code-recommended)]

**Comment by vingerha** [comment]
essaye ça si t'as l'option pour tester..
https://forum.hacf.fr/t/beta-integration-pronote/24682/672

**Comment by Ekomak** [comment]
> essaye ça si t'as l'option pour tester.. https://forum.hacf.fr/t/beta-integration-pronote/24682/672

Je viens de faire le test avec le QR Code. La connexion se fait bien. Bravo !!!
Si besoin de retours ou de logs de l'installation sur mon HA, je suis disponible.

Merci encore.

**Comment by vingerha** [comment]
Top, j'attend d'autres tests et j'ai encore qq améliorations (le courant ne supporte q'un enfant)

**Comment by delphiki** [comment]
Hello,

La version 0.10.0 gère la connexion via QR Code

**Comment by Ekomak** [comment]
Merci et bravo @delphiki  & @vingerha l'intégration fonctionne très bien.

**Comment by Tirguy** [comment]
Nickel !!!
La connexion fonctionne parfaitement sur les écoles de Paris.
Quelques entités ne semblent pas accessible ou disponible, lié à ???

Bravo encore à tous

**Comment by Nemesis24** [comment]
Tout est parfait merci 💯
