### ISSUE TITLE
Erreur après upgrade en 0.8

### ISSUE THREAD

**Issue by HermesHonshappo** [delphiki/hass-pronote#32]
Hello

Tout marchait bien pour moi en 0.7
Upgrade en 0.8, reboot, et là j'ai ça comme erreur donnée par HA dans les notifications:
```
Home Assistant Core
Unable to prepare setup for platform pronote.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
15:36:48 – (ERROR) setup.py
```

Les sensors associés au gamin sont maintenant absents de HA.

Je vais tenter d'effacer et remettre l'intégration, on va voir si ça change quelque chose.

EDIT: pareil après plusieurs reboot, suppression et réinstallation de la v0.8. Aucun sensor pronote créé

Suppression, puis réinstall de la 0.7, et ça fonctionne de nouveau, et les sensors sont de nouveau créés.

**Comment by delphiki** [comment]
Hello,

je pense que ta version d’HA ne doit pas être à jour

**Comment by HermesHonshappo** [comment]
Ah ok, je ne pensais pas qu'il y avait une dépendance. Upgrade de HA, re-upgrade de l'add-on (en v0.8.1), et effectivement, ça fonctionne
