### ISSUE TITLE
Toulouse Edu problème de connection

### ISSUE THREAD

**Issue by aginies** [delphiki/hass-pronote#33]
Bonjour,
voici mon probleme, désormais il faut passer via educonnect, j'ai eu beau essayer l'académie toulouse EDu, cela ne fonctionne pas.
voici les logs que j'ai dans HA:

sept. 22 15:47:44 linux-t430 home-assistant[26445]: 2023-09-22 15:47:44.184 DEBUG (SyncWorker_11) [pronotepy.ent.generic_func] [ENT https://cas.mon-ent-occitanie.fr/login?selection=TOULO-EDU_parent_eleve&service=https://example.com/] Logging in with XXXXXXX
sept. 22 15:47:44 linux-t430 home-assistant[26445]: 2023-09-22 15:47:44.546 DEBUG (SyncWorker_11) [pronotepy.ent.generic_func] [EduConnect https://educonnect.education.gouv.fr/idp/profile/SAML2/POST/SSO?execution=e1s1] Logging in with XXXXXX
sept. 22 15:47:45 linux-t430 home-assistant[26445]: 2023-09-22 15:47:45.087 CRITICAL (SyncWorker_11) [custom_components.pronote.config_flow] Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.

**Comment by aginies** [comment]
il me met: "Erreur d'authentification"

J'ai testé et cela fonctionne si je le fais directement sur le site educonnect donc le couple mot de passe login est bon.

**Comment by boulete31** [comment]
Bonjour,

Pareil de mon côté avec https://xxxxxx.index-education.net/pronote/ pour https://cas.ecollege.haute-garonne.fr/ depuis que l'authentification se fait via educonnect https://educonnect.education.gouv.fr/.

**Comment by alegeay** [comment]
Pareil de mon coté pour l'académie Orléans-tours qui est passé avec https://educonnect.education.gouv.fr/.

**Comment by vingerha** [comment]
essaie v0.10.0 avec QR Code

**Comment by aginies** [comment]
cela fonctionne avec le QR code!
merci pour ce fix.
