### ISSUE TITLE
Invalid URL when trying to connect to pronote (val_doise)

### ISSUE THREAD

**Issue by Mattieug** [delphiki/hass-pronote#5]
Hi,

I am trying to configure pronote component.

I have verified all needed information as explained in docs. My user and password are working fine when connecting directly to pronote web app.

When trying to configure the component, I fill fields as following :

>URL : https://0951403j.index-education.net/pronote/
>User : firtname.lastname
>Password : mypassword
>ENT : val_doise

When validating, I caught this error : "Erreur d'authentification"

In home assistant logs, I have following error : 

>Logger: custom_components.pronote.config_flow
>Source: custom_components/pronote/config_flow.py:60
>Integration: Pronote ([documentation](https://github.com/delphiki/hass-pronote), [issues](https://github.com/delphiki/hass->pronote/issues))
>First occurred: 00:53:04 (11 occurrences)
>Last logged: 01:56:19

>HTTPSConnectionPool(host='ent0951403j.moncollege.valdoise.frparent.html', port=443): Max retries exceeded with url: / >(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5b12d610>: Failed to establish a new >connection: [Errno -2] Name does not resolve'))
>Unable to connect to pronote, please try again later
>Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
>Fail to connect with CAS https://cas.moncollege.valdoise.fr/login?selection=eleveparent : probably wrong login information

It seems that there is a missing '/' between url and parent.html. Plus, the URL used is not the one I specified.

Could you please have a look on this issue ?

Thanks,

Mattieu.

**Comment by emylive** [comment]
Hi,
It's seem I have the same problem :


Logger: custom_components.pronote.config_flow
Source: custom_components/pronote/config_flow.py:60
Integration: Pronote (documentation, issues)
First occurred: 5 septembre 2023 à 22:11:58 (10 occurrences)
Last logged: 18:12:58

Fail to connect with Open NG https://moncollege-ent.var.fr/auth/login : probably wrong login information
Unable to connect to pronote, please try again later
Fail to connect with EduConnect : probably wrong login information

Thanks for your help

**Comment by emylive** [comment]
It's work now with the release 0.4.1!
Thanks a lot!
