### ISSUE TITLE
Integration ne fonctionne plus depuis la dernière update et bloque HA

### ISSUE THREAD

**Issue by Wobak** [delphiki/hass-pronote#50]
Bonjour,

Depuis la dernière mise à jour, j'ai le message suivant dans les logs : 
2023-10-21 22:33:58.968 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: pronote

Et mon home assistant n'arrive plus à fonctionner correctement.

Impossible d'aller dans les devices & services pour désactiver pronote, et du coup c'est tout cassé.

Comment faire ? 

Merci, 

Détails : 
Version docker
Home Assistant 2023.10.4
Frontend 20231005.0 - latest

**Comment by Ekomak** [comment]
Bonjour 

J'ai le même problème et voici un moyen de faire fonctionner HA en attendant un correctif.

Pour permettre à HA de fonctionner à nouveau, redémarre 
Il faudra peut-être le faire en 2 fois avec ces étapes ci-dessous sans jamais laisser le temps à tous les modules de se charger notamment celui de Probote

- Démarrage HA
- Suppression de l'intégration Pronote dans les services
- Redémarrage 
- Désinstallation de Pronote dans HACS
- Redémarrage de HA

Ensuite attendre un correctif

**Comment by Wobak** [comment]
Sauf que je n'arrive pas à charger le module pronote, et que du coup je reste bloqué au démarrage, impossible d'aller virer l'integration...

**Comment by Wobak** [comment]
OK J'ai résolu en téléchargeant la v12.1 et en poussant les fichiers modifiés dans custom_component !
