### ISSUE TITLE
Integration crashes when every class next day is canceled

### ISSUE THREAD

**Issue by Tandonnet** [delphiki/hass-pronote#52]
The whole class is marked absent the next day, so the next alarm sensor cannot initialize and the whole integration fails. Reverting back to 0.12.1 fixes the issue.

**Comment by Torp1lle** [comment]
Maybe something similar in my situation :
Pour plus de précisions. J'ai deux enfants, Louison et Pénélope. Donc pour Louison pas de problème pour l'ajout en QR code en 13.2. Hier soir, immédiatement après j'ai ajouté Pénélope. Aucun problème. Tous les sensors OK et affichage des infos correct.
Erreur ce matin ça ne marche plus uniquement pour Pénélope.
J'ai viré les deux configs, refait, avec différents codes pour le QR code, toujours la même chose. Quand j'ajoute Louison on me demande une pièce. Mais pas pour Pénélope.
La seule différence notable entre hier et aujourd'hui c'est dans l'agenda de Pénélope. **Elle a une sortie de classe toute la journée. Ce n'est pas répertorié comme une matière.** J'ai bien l'impression que c'est ça l'erreur, donc mon problème est peut être un autre bug car ce n'est plus "initialisation' mais bien 'echec de la configuration'. Comment je créée un autre 'issue'?

**Comment by tdelaux** [comment]
Bonjour,
je pense que c'est la trace liée au problème.
Ma fille a tous les cours de la semaine annulés car elle est en stage.


```
Logger: custom_components.pronote.coordinator
Source: helpers/update_coordinator.py:290
Integration: Pronote ([documentation](https://github.com/delphiki/hass-pronote), [issues](https://github.com/delphiki/hass-pronote/issues))
First occurred: 6 novembre 2023 à 16:45:34 (628 occurrences)
Last logged: 06:47:52

Unexpected error fetching XXX Sophie (via compte parent) data: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/coordinator.py", line 183, in _async_update_data
    next_day_alarm = get_day_start_at(self.data['lessons_next_day']) - timedelta(minutes=alarm_offset)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'
```

**Comment by Tandonnet** [comment]
@tdelaux Idem pour moi, même problème et même erreur

**Comment by delphiki** [comment]
Ok, je vois d'où vient l'erreur, j'essaye de faire un fix asap!

**Comment by delphiki** [comment]
Le bug devrait être corrigé avec la version 0.13.4 :+1:

**Comment by Tandonnet** [comment]
Effectivement, problème réglé !
