### ISSUE TITLE
Erreur 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by eriklouise** [delphiki/hass-pronote#56]
Bonjour,

Depuis ce matin, apres màj en version 0.13.3, j'ai l'erreur suivante qui apparait:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/coordinator.py", line 183, in _async_update_data
    next_day_alarm = get_day_start_at(self.data['lessons_next_day']) - timedelta(minutes=alarm_offset)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'
```

Ayant 2 enfants scolarisés dans 2 établissements différents, cela ne se produit que sur un seul des 2 comptes. J'ai tenté de supprimer et recréer le compte en erreur avec les méthodes URL+Password et QRCode mais j'arrive a la même erreur à chaque fois.

**Comment by delphiki** [comment]
Hello,

Effectivement, je vois d'où ça peut venir, je vais regarder pour corriger ça :+1:

**Comment by delphiki** [comment]
Normalement corrigé dans la version 0.13.4 :+1:

**Comment by eriklouise** [comment]
Effectivement, ça fonctionne impeccable ! 👍
