### ISSUE TITLE
heure local plutot que gmt....

### ISSUE THREAD

**Issue by mcarbonneaux** [delphiki/hass-pronote#58]
super plugin !!!

y a moyen d'avoir l'heure local plutot que gmt ?

**Comment by GaPhi** [comment]
datetime.astimezone()

**Comment by mcarbonneaux** [comment]
_next_alarm for exemple are in gmt not local time.

**Comment by delphiki** [comment]
Pour moi le `next_alarm` est correct, vu qu'il y a une anticipation par défaut de 60 minutes (configurable dans les options) sur l'heure de début des cours du prochain jour.
