### ISSUE TITLE
Location Evènement Calendrier Hass

### ISSUE THREAD

**Issue by tdelaux** [delphiki/hass-pronote#84]
Bonjour,
les évènements des calendriers Hass n'ont pas de champ "location".
![image](https://github.com/user-attachments/assets/7eb13b7e-957d-4a8b-b398-6f5c08f0f8cc)

L'information classroom est donc perdue lors de l'affectation dans calendar.py: 
![image](https://github.com/user-attachments/assets/933dced7-5528-4d6a-b054-2099e56048c3)

Je propose de rajouter la localisation  suite au nom du prof dans la description avec quelque chose comme ça : 
```
    return CalendarEvent(
        summary=lesson_name,
        description=f"{lesson.teacher_name} - Salle {lesson.classroom}",
        start=tz.localize(lesson.start),
        end=tz.localize(lesson.end),
    )
```

Merci

**Comment by delphiki** [comment]
Je ferme vu que la PR a été mergée 👍
