### ISSUE TITLE
Pas de mise à jour

### ISSUE THREAD

**Issue by GaPhi** [delphiki/hass-pronote#9]
Bonjour,

Tout d'abord, beau boulot !

Sur mon installation Raspberry Pi3B+Docker+HA+HACS+Pronote, les données ne sont pas mises à jour...
D'où cela peut-il venir et comment corriger ? Je n'ai pas identifié le mécanisme de mise à jour dans les sources (mais je ne suis pas familier du python)

Merci !

**Comment by GaPhi** [comment]
Finalement, après un redémarrage de HA, la mise à jour est tombée en marche ;-)

Peut-être que d'autres auront eu le même souci et pourront profiter de cette solution simple !

**Comment by delphiki** [comment]
Hello @GaPhi,

Il y avait bien un souci de mise à jour automatique (les màj se font au redémarrage de HA, mais c'est tout), il faut que tu mettes à jour vers la dernière version pour que ça fonctionne correctement.
